# Generated by Django 5.2 on 2025-07-15 11:37

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TranslatedImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("original_image", models.FileField(upload_to="originals/")),
                ("translated_image", models.FileField(upload_to="translated_images/")),
                (
                    "translated_text_file",
                    models.FileField(upload_to="translated_texts/"),
                ),
                ("original_text", models.TextField(blank=True)),
                ("translated_text", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
