# Generated by Django 5.2 on 2025-07-18 06:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TranslatedImage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image_hash", models.CharField(db_index=True, max_length=64)),
                ("source_language", models.CharField(blank=True, max_length=10)),
                (
                    "target_language",
                    models.CharField(
                        choices=[
                            ("uk", "Українська"),
                            ("en", "Англійська"),
                            ("de", "Німецька"),
                            ("fr", "Французька"),
                            ("es", "Іспанська"),
                            ("it", "Італійська"),
                            ("pl", "Польська"),
                        ],
                        default="uk",
                        max_length=10,
                    ),
                ),
                ("original_image", models.FileField(upload_to="originals/")),
                ("translated_image", models.FileField(upload_to="translated_images/")),
                ("original_text_file", models.FileField(upload_to="original_texts/")),
                (
                    "translated_text_file",
                    models.FileField(upload_to="translated_texts/"),
                ),
                ("original_text", models.TextField(blank=True)),
                ("translated_text", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "image_hash", "target_language")},
            },
        ),
    ]
