# Generated by Django 5.2 on 2025-07-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="translatedimage",
            name="original_text_file",
            field=models.FileField(default=0, upload_to="original_texts/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="translatedimage",
            name="target_language",
            field=models.CharField(default="ru", max_length=10),
        ),
        migrations.AlterField(
            model_name="translatedimage",
            name="image_hash",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name="translatedimage",
            unique_together={("image_hash", "target_language")},
        ),
    ]
