# Generated by Django 5.2 on 2025-07-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translator", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translatedimage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
