# Generated by Django 5.2 on 2025-07-15 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translator", "0003_alter_translatedimage_target_language"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="translatedimage",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="translatedimage",
            name="user",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="translatedimage",
            unique_together={("user", "image_hash", "target_language")},
        ),
    ]
