# Generated by Django 5.2 on 2025-07-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translator", "0005_translatedimage_source_language_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translatedimage",
            name="target_language",
            field=models.CharField(
                choices=[
                    ("uk", "Українська"),
                    ("en", "Англійська"),
                    ("de", "Німецька"),
                    ("fr", "Французька"),
                    ("es", "Іспанська"),
                    ("it", "Італійська"),
                    ("pl", "Польська"),
                ],
                default="uk",
                max_length=10,
            ),
        ),
    ]
